addons:
  apt:
    packages:
      - fonts-sil-doulos
      - lmodern
      - pgf
      - texlive-base
      - texlive-science
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-lang-greek
      - texlive-lang-czechslovak
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-math-extra
      - texlive-xetex 
# for tests
      - latex-beamer
      - python-matplotlib
      - python-numpy


before_install:
  # we need poppler-utils >= 0.25
  - sudo add-apt-repository -y ppa:alexis-via/poppler-utils-backport
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils

install:

before_script:

script:
  - make test

after_failure:
  - cat ./tests/out/*.log
  - echo "Test failed, see respective PNGs"
